server:
  port: 8081

spring:
  datasource:
    username: root
    data-password: a70490238A!
    url: jdbc:mysql://8.130.48.31:3306/flash20?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
  